---@alias WFTheme "default"|"space"|"chad"

---@class WFHighlight
---@field WFNormal string
---@field WFNormal string
---@field WFFloatBorder string
---@field WFFloatBorderFocus string
---@field WFComment string
---@field WFWhichRem string
---@field WFWhichOn string
---@field WFFuzzy string
---@field WFFuzzyPrompt string
---@field WFFocus string
---@field WFFreeze string
---@field WFWhichObjCounter string
---@field WFWhichDesc string
---@field WFSeparator string
---@field WFGroup string
---@field WFWhichUnique string
---@field WFExpandable string
---@field WFTitleOutput string
---@field WFTitleWhich string
---@field WFTitleFuzzy string
---@field WFTitleFreeze string

---@class WFConfig
---@field theme? WFTheme
---@field highlight? WFHighlight
